version: "3.8"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: bash -c "
      while !</dev/tcp/db/5432; do sleep 1; done;
      ./main -rt
      "

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata: